### PR TITLE
Added the index.js file. If the user doesn't have the coffee-script i…

### PR DESCRIPTION
**Pull request by fraterblack**
…nstalled, a problem appears.

### CODE REVIEW

**Comment by joscha** [comment]
0.0.6 has a dev-only coffee dependency on prepublish. Coffee is not needed when installing the package from npm.

**Comment by fraterblack** [comment]
I installed from npm, but the index.js file didn't appear.
The problem is the same in this issue: https://github.com/joscha/gulp-rewrite-css/issues/14

**Comment by joscha** [comment]
:-/ Let me look into this again. Can you check the build process? Does
prepublish create that file for you? It should be in lib/

**Comment by fraterblack** [comment]
I updated my NodeJs and the problem was solved. Thank you so much.

**Pull request closed without merging**
